<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AirClip.Platform.Windows</RootNamespace>
    <UseWPF>true</UseWPF>
    <!-- Required by the LibraryImport source generator. -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirClip.Core\AirClip.Core.csproj" />
  </ItemGroup>

</Project>
